#pragma once

#include <random>
#include <vector>
#include <chrono>
#include <iostream>
#include <cmath>
#include <string>
#include <fstream>
#include <filesystem>
#include <stdexcept>
#include <map>
#include <unordered_map>
#include <memory>
#include <sstream>
#include <queue>
#include <utility>
#include <algorithm>
#include <semaphore>
#include <thread>
#include <condition_variable>
#include <cstring>